// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrcgmzzxfvmageolncpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyY2dtenp4ZnZtYWdlb2xuY3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3Nzc1OTAsImV4cCI6MjA3MTM1MzU5MH0.5q5K9MeW3t4Fn6qB7DuD6hKHGITnSwpeUiNLcqD-aV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});